# Generated by Django 4.0.5 on 2022-06-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.CharField(max_length=100, null=True, verbose_name='Каллорийность'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='compound',
            field=models.TextField(max_length=250, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.CharField(max_length=100, null=True, verbose_name='Масса'),
        ),
    ]
