# Generated by Django 4.0.5 on 2022-06-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dish_calories_alter_dish_compound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='menu.dish', verbose_name='Блюдо'),
        ),
    ]
