# Generated by Django 4.0.5 on 2022-06-16 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_news_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='entrance',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительная информация по входу'),
        ),
        migrations.AddField(
            model_name='news',
            name='when',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Когда'),
        ),
    ]
