# Generated by Django 4.0.5 on 2022-06-22 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_news_entrance_news_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 12, 39, 56, 269759), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='when',
            field=models.CharField(default=datetime.datetime(2022, 6, 22, 12, 39, 56, 269759), max_length=100, verbose_name='Когда'),
        ),
    ]
