# Generated by Django 4.0.5 on 2022-07-01 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_news_published_date_alter_news_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 15, 36, 22, 299330), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='when',
            field=models.CharField(default=datetime.datetime(2022, 7, 1, 15, 36, 22, 299330), max_length=100, verbose_name='Когда'),
        ),
    ]
