# Generated by Django 4.0.5 on 2022-06-22 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 22, 12, 39, 56, 195758), verbose_name='Дата'),
        ),
    ]
