# Generated by Django 4.0.5 on 2022-06-22 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 22, 13, 42, 31, 867854), verbose_name='Дата'),
        ),
    ]
